<!doctype html>
<html lang="en">
    <head>
        <title><?= $this->tag->getTitle() ?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="container">
                        <ul class="navbar-nav">
                            <li class="nav-text">
                                <a class="nav-link" href="/">Home</a>
                            </li>
                            <li class="nav-text">
                                <a class="nav-link" href="/example">Example</a>
                            </li>
                            
                            <?php if ($this->getDI()->get('session')->role === \App\Service\Acl\Role::ADMIN) : ?>
                                <li class="nav-text">
                                    <a class="nav-link" href="/admin">Admin</a>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div class="navbar-nav">
                            <span class="navbar-text">
                                <a class="nav-link" href="/logout">Logout</a>
                            </span>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <div>
            <?= $this->getContent() ?>
        </div>
    </body>
</html>
