<div class="container col-md-6">

    <h2 class="m-3">Please log in to proceed</h2>

    <form method="post">
        <div class="form-group">
            <?php
                echo $form->render(
                    'username',
                    [
                    'value' => $error->username ?? null
                    ]
                )
            ?>
        </div>

        <div class="form-group">
            <?php
                echo $form->render(
                    'password',
                    [
                    'value' => $error->password ?? null
                    ]
                )
            ?>
        </div>

        <div class="text-danger text-center">
            <?= $error->msg ?? null ?>
        </div>

        <?= $form->render('submit') ?>
    </form>
</div>
