<div class="container mt-5">
    <form class="col-md-6" method="post">

        <div class="form-group">
            <?php
                echo $form->render(
                    'username',
                    [
                      'value' => $error->username ?? null
                    ]
                )
            ?>
        </div>

        <div class="form-group">
            <?php
                echo $form->render(
                    'password',
                    [
                      'value' => $error->password ?? null
                    ]
                )
            ?>
        </div>

        <div class="text-danger text-center">
            <?= $error->msg ?? null ?>
        </div>

        <?= $form->render('submit') ?>
    </form>
</div>
